# Generated by Django 4.2 on 2023-07-25 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writers_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Writer',
        ),
    ]
